version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:80"  # <-- fix port mapping
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo_container:27017/room_alloc  # <-- fix variable
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
